// src/components/AddShortcut.vue
<template>
  <a-modal :visible="visible" title="Add Shortcut" @ok="closeModal" @cancel="closeModal">
    <p>Some contents...</p>
    <p>Some contents...</p>
    <p>Some contents...</p>
  </a-modal>
</template>

<script>
export default {
  name: 'AddShortcut',
  props: ['open', 'close'],
  data() {
    return {
      visible: false
    }
  },
  watch: {
    open: function () {
      this.openModal();
    },
    close: function () {
      this.closeModal();
    }
  },
  methods: {
    openModal() {
      this.visible = true
    },
    closeModal() {
      this.visible = false
    }
  }
}
</script>

// electron-react/src/component/AddShortcutComponent.tsx
import { Modal } from "antd";

import "../style/add-style.scss"

function AddShortcutComponent(props: { isOpen: boolean; closeModal: any }) {
  const close = () => {
    props.closeModal();
  };

  return (
    <Modal
      open={props.isOpen}
      title="Add Shortcut"
      onCancel={close}
      onOk={close}
    >
      <div className="add-modal-content">
        <p>Are you sure add all data?</p>
      </div>
    </Modal>
  );
}
export default AddShortcutComponent;
