// src/components/ImportShortcut.vue
<template>
  <a-modal
    :visible="visible"
    title="Import Shortcut"
    @cancel="closeModal"
    @ok="importAll"
  >
    <div class="ant-modal-body">
      <a-icon type="import" class="icon" />
      <p>Are you sure import all data?</p>
    </div>
  </a-modal>
</template>

<script>
import { showOpenDialog, importFile } from "@/service/utils";
import { addShortcut } from "@/storage/crud";

export default {
  name: "ImportShortcut",
  props: ["open", "close"],
  emits: ["refresh"],
  data() {
    return {
      visible: false,
    };
  },
  watch: {
    open: function () {
      this.openModal();
    },
    close: function () {
      this.closeModal();
    },
  },
  methods: {
    openModal() {
      this.visible = true;
    },
    closeModal() {
      this.visible = false;
    },
    importAll() {
      const options = {
        title: "Import shortcuts",
        buttonLabel: "Import",
        filters: [{ extensions: ["json"] }],
        properties: ["openFile"],
      };
      showOpenDialog(options).then(({ filePaths }) => {
        if (filePaths != undefined && filePaths.length > 0) {
          const filename = filePaths[0];
          importFile(filename, "utf-8").then((data) => {
            const rows = JSON.parse(data);
            rows.forEach((row) =>
              addShortcut(row.action, row.icon, row.size, row.title, false)
            );
            this.$notification.success({
              message: "All data imported from file " + filename,
            });
            this.refresh();
            this.closeModal();
          });
        }
      });
    },
    refresh() {
      this.$emit("refresh");
    },
  },
};
</script>

<style lang="scss" scoped>
.ant-modal-body {
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  gap: 10px;
}

.icon {
  color: #096dd9;
  font-size: 25px;
}
</style>

// electron-react/src/component/ImportShortcutComponent.tsx
import { Modal } from "antd";
import { ImportOutlined } from "@ant-design/icons";
import { addShortcut } from "../storage/crud";
import { importFile, showOpenDialog } from "../service/utils";
import { notificationSuccess } from "./Notification";

import "../style/import-style.scss";

function ImportShortcutComponent(props: {
  isOpen: boolean;
  closeModal: any;
  refresh: any;
}) {
  const close = () => {
    props.closeModal();
  };

  const importAll = () => {
    const options = {
      title: "Import shortcuts",
      buttonLabel: "Import",
      filters: [{ extensions: ["json"] }],
      properties: ["openFile"],
    };
    showOpenDialog(options).then(({ filePaths }) => {
      if (filePaths != undefined && filePaths.length > 0) {
        const filename = filePaths[0];
        importFile(filename, "utf-8").then((data) => {
          const rows = JSON.parse(data);
          rows.forEach((row: any) =>
            addShortcut(
              row.action,
              row.color,
              row.icon,
              row.size,
              row.title,
              false
            )
          );
          props.refresh();
          close();
          notificationSuccess({
            message: "All data imported from file " + filename,
          });
        });
      }
      close();
    });
  };

  return (
    <Modal
      open={props.isOpen}
      title="Import Shortcut"
      onCancel={close}
      onOk={importAll}
    >
      <div className="import-modal-content">
        <ImportOutlined className="icon" />
        <p>Are you sure import all data?</p>
      </div>
    </Modal>
  );
}

export default ImportShortcutComponent;
