// src/components/Menu.vue
<template>
  <a-menu
    :selectedKeys="current"
    mode="horizontal"
    theme="dark"
    class="menu-container"
  >
    <a-sub-menu key="settings">
      <template #icon>
        <a-icon type="setting" theme="filled" :style="iconStyle" />
      </template>
      <template #title>Settings</template>
      <a-menu-item-group title="Shortcuts">
        <a-menu-item key="add" @click="openAddDialog">Add</a-menu-item>
      </a-menu-item-group>
      <a-menu-item-group title="DB Configuration">
        <a-menu-item key="clear" @click="openClearDialog">Clear</a-menu-item>
        <a-menu-item key="import" @click="openImportDialog">Import</a-menu-item>
        <a-menu-item key="export" @click="openExportDialog">Export</a-menu-item>
      </a-menu-item-group>
    </a-sub-menu>
    <add-shortcut :open="addTrigger" @refresh="refresh" />
    <clear-shortcut :open="clearTrigger" @refresh="refresh" />
    <import-shortcut :open="importTrigger" @refresh="refresh" />
    <export-shortcut :open="exportTrigger"/>
  </a-menu>
</template>

<script>
import { ref } from "vue";
import AddShortcut from "@/components/AddShortcut";
import ClearShortcut from "@/components/ClearShortcut";
import ImportShortcut from "@/components/ImportShortcut";
import ExportShortcut from "@/components/ExportShortcut";
export default {
  name: "MenuComponent",
  emits: ["refresh"],
  components: {
    AddShortcut,
    ClearShortcut,
    ExportShortcut,
    ImportShortcut,
  },
  data() {
    return {
      current: ref(["shortcuts"]),
      iconStyle: {
        fontSize: "24px",
        color: "#096dd9",
      },
      addTrigger: false,
      clearTrigger: false,
      importTrigger: false,
      exportTrigger: false,
    };
  },
  methods: {
    openAddDialog() {
      this.addTrigger = !this.addTrigger;
    },
    openClearDialog() {
      this.clearTrigger = !this.clearTrigger;
    },
    openImportDialog() {
      this.importTrigger = !this.importTrigger;
    },
    openExportDialog() {
      this.exportTrigger = !this.exportTrigger;
    },
    refresh() {
      this.$emit("refresh");
    }
  },
};
</script>

<style lang="scss" scoped>
.menu-container {
  padding: 0.5rem;
}
</style>

// electron-react/src/component/MenuComponent.tsx
import { Menu } from "antd";
import { useState } from "react";
import AddShortcutComponent from "./AddShortcutComponent";
import ClearShortcutComponent from "./ClearShortcutComponent";
import ExportShortcutComponent from "./ExportShortcutComponent";
import ImportShortcutComponent from "./ImportShortcutComponent";

const items = [
  {
    label: "Settings",
    key: "settings",
    children: [
      {
        type: "group",
        label: "Shortcuts",
        key: "shortcuts",
        children: [
          {
            label: "Add",
            key: "add",
          },
        ],
      },
      {
        type: "group",
        label: "DB Configuration",
        key: "configuration",
        children: [
          {
            label: "Refresh",
            key: "refresh",
          },
          {
            label: "Import",
            key: "import",
          },
          {
            label: "Export",
            key: "export",
          },
          {
            label: "Clear",
            key: "clear",
          },
        ],
      },
    ],
  },
];

const MenuComponent = () => {
  const [addDialog, setAddDialog] = useState(false);
  const [clearDialog, setClearDialog] = useState(false);
  const [exportDialog, setExportDialog] = useState(false);
  const [importDialog, setImportDialog] = useState(false);

  const openAddDialog = () => {
    setAddDialog(!addDialog);
  };
  const openClearDialog = () => {
    setClearDialog(!clearDialog);
  };
  const openExportDialog = () => {
    setExportDialog(!exportDialog);
  };
  const openImportDialog = () => {
    setImportDialog(true);
  };

  const onClick = (e: any) => {
    if (e.key == "add") {
      openAddDialog();
    }
    if (e.key == "clear") {
      openClearDialog();
    }
    if (e.key == "export") {
      openExportDialog();
    }
    if (e.key == "import") {
      openImportDialog();
    }
  };

  return (
    <>
      <Menu
        onClick={onClick}
        selectedKeys={["shortcuts"]}
        mode="horizontal"
        theme="dark"
        items={items}
      ></Menu>
      <AddShortcutComponent open={addDialog} />
      <ClearShortcutComponent open={clearDialog} />
      <ExportShortcutComponent open={exportDialog} />
      <ImportShortcutComponent isOpen={importDialog} closeModal={() => setImportDialog(false)} />
    </>
  );
};

export default MenuComponent;
