// src/component/FooterComponent.tsx
import { Tooltip } from "antd";
import { Button, Divider } from "antd";
import {
  PlusOutlined,
  DeleteOutlined,
  ExportOutlined,
  ImportOutlined,
} from "@ant-design/icons";

import { Component } from "react";
import ImportShortcutComponent from "./ImportShortcutComponent";
import AddShortcutComponent from "./AddShortcutComponent";
import ClearShortcutComponent from "./ClearShortcutComponent";
import ExportShortcutComponent from "./ExportShortcutComponent";

import "../style/footer-style.scss";

class FooterComponent extends Component<any, any> {
  constructor(props: any) {
    super(props);

    this.state = {
      addDialog: false,
      clearShortcutDialog: false,
      clearLayoutDialog: false,
      exportDialog: false,
      importDialog: false,
    };
  }

  openAddDialog = () => {
    this.setState({ addDialog: true });
  };
  openClearDialog = () => {
    this.setState({ clearShortcutDialog: true });
  };
  openExportDialog = () => {
    this.setState({ exportDialog: true });
  };
  openImportDialog = () => {
    this.setState({ importDialog: true });
  };

  render() {
    return (
      <div className="footer-container">
        <div className="footer-right-item">
          <span className="footer-counter-item">{this.props.size}</span>
          <Divider type="vertical" className="action-divider" />
          <Tooltip title="Add">
            <Button
              className="action-button"
              shape="circle"
              size={"large"}
              type="primary"
              icon={<PlusOutlined />}
              onClick={this.openAddDialog}
            ></Button>
          </Tooltip>
          <Divider type="vertical" className="action-divider" />
          <Tooltip title="Import">
            <Button
              className="action-button"
              shape="circle"
              size={"large"}
              type="primary"
              icon={<ImportOutlined />}
              onClick={this.openImportDialog}
            ></Button>
          </Tooltip>
          <Tooltip title="Export">
            <Button
              className="action-button"
              shape="circle"
              size={"large"}
              type="primary"
              icon={<ExportOutlined />}
              onClick={this.openExportDialog}
            ></Button>
          </Tooltip>
          <Divider type="vertical" className="action-divider" />
          <Tooltip title="Clear Shortcut">
            <Button
              className="action-button"
              shape="circle"
              size={"large"}
              type="primary"
              icon={<DeleteOutlined />}
              onClick={this.openClearDialog}
            ></Button>
          </Tooltip>
        </div>
        <AddShortcutComponent
          isOpen={this.state.addDialog}
          closeModal={() => this.setState({ addDialog: false })}
          refresh={this.props.refresh}
        />
        <ImportShortcutComponent
          isOpen={this.state.importDialog}
          closeModal={() => this.setState({ importDialog: false })}
          refresh={this.props.refresh}
        />
        <ExportShortcutComponent
          isOpen={this.state.exportDialog}
          closeModal={() => this.setState({ exportDialog: false })}
          refresh={this.props.refresh}
        />
        <ClearShortcutComponent
          isOpen={this.state.clearShortcutDialog}
          closeModal={() => this.setState({ clearShortcutDialog: false })}
          refresh={this.props.refresh}
        />
      </div>
    );
  }
}

export default FooterComponent;

// electron-vue/src/components/FooterComponent.vue
<template>
  <div class="footer-container">
    <span class="footer-left-item">Shortcut size {{ size }}</span>
    <div class="footer-right-item">
      <a-tooltip title="Add">
        <a-button class="action-button" shape="circle" :size="'large'" type="primary" icon="plus" theme="filled"
          @click="openAddDialog">
        </a-button>
      </a-tooltip>
      <a-divider type="vertical" class="action-divider"/>
      <a-tooltip title="Refresh">
        <a-button class="action-button" shape="circle" :size="'large'" type="primary" icon="reload" theme="filled"
          @click="refresh">
        </a-button>
      </a-tooltip>
      <a-tooltip title="Import">
        <a-button class="action-button" shape="circle" :size="'large'" type="primary" icon="import" theme="filled"
          @click="openImportDialog">
        </a-button>
      </a-tooltip>
      <a-tooltip title="Export">
        <a-button class="action-button" shape="circle" :size="'large'" type="primary" icon="export" theme="filled"
          @click="openExportDialog">
        </a-button>
      </a-tooltip>
      <a-divider type="vertical" class="action-divider"/>
      <a-tooltip title="Clear">
        <a-button class="action-button" shape="circle" :size="'large'" type="primary" icon="delete" theme="filled"
          @click="openClearDialog">
        </a-button>
      </a-tooltip>
    </div>
    <add-shortcut :open="addTrigger" @refresh="refresh" />
    <clear-shortcut :open="clearTrigger" @refresh="refresh" />
    <import-shortcut :open="importTrigger" @refresh="refresh" />
    <export-shortcut :open="exportTrigger" />
  </div>
</template>

<script>
import AddShortcut from "@/components/AddShortcut";
import ClearShortcut from "@/components/ClearShortcut";
import ImportShortcut from "@/components/ImportShortcut";
import ExportShortcut from "@/components/ExportShortcut";
export default {
  name: "FooterComponent",
  props: ['size'],
  emits: ["refresh"],
  components: {
    AddShortcut,
    ClearShortcut,
    ExportShortcut,
    ImportShortcut,
  },
  data() {
    return {
      data: 0,
      addTrigger: false,
      clearTrigger: false,
      importTrigger: false,
      exportTrigger: false,
    };
  },
  watch: {
    size: function (data) {
      this.data = data;
    },
  },
  methods: {
    openAddDialog() {
      this.addTrigger = !this.addTrigger;
    },
    openClearDialog() {
      this.clearTrigger = !this.clearTrigger;
    },
    openImportDialog() {
      this.importTrigger = !this.importTrigger;
    },
    openExportDialog() {
      this.exportTrigger = !this.exportTrigger;
    },
    refresh() {
      this.$emit("refresh");
    }
  }
};
</script>

<style lang="scss" scoped>
.footer-container {
  display: flex;
  min-width: 20px;
  width: 100%;
  justify-content: space-between;
}

.footer-left-item {
  display: flex;
  align-items: center;
  font-weight: bold;
}

.footer-right-item {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  width: 50%;
  gap: 5px;
}

.action-button {
  border-color: #001529;
  background-color: #001529;
}

.action-divider {
  background-color: rgba(0, 0, 0, 0.65);
  width: 2px;
  height: 25px;
}
</style>
