// electron-react/src/component/ExportShortcutComponent.tsx
import { Modal } from "antd";
import { ExportOutlined } from "@ant-design/icons";
import { getAllShortcut } from "../storage/crud";
import { exportFile, showSaveDialog } from "../service/utils";
import openNotification from "./Notification";

import "../style/export-style.scss"

function ExportShortcutComponent(props: { isOpen: boolean; closeModal: any }) {
  const close = () => {
    props.closeModal();
  };
  const exportAll = () => {
    getAllShortcut().then((rows) => {
      const options = {
        title: "Export shortcuts",
        defaultPath: "export_shortcuts.json",
        buttonLabel: "Export",
        filters: [{ name: "json", extensions: ["json"] }],
      };
      showSaveDialog(options).then(({ filePath }) => {
        if (filePath != undefined && filePath != "") {
          exportFile(filePath, JSON.stringify(rows), "utf-8").then(() => {
            openNotification({
              message: "All data exported successfully here " + filePath,
            });
          });
        }
      });
      close();
    });
  };

  return (
    <Modal
      open={props.isOpen}
      title="Export Shortcut"
      onCancel={close}
      onOk={exportAll}
    >
      <div className="export-modal-content">
        <ExportOutlined className="icon" />
        <p>Are you sure export all data?</p>
      </div>
    </Modal>
  );
}
export default ExportShortcutComponent;

// src/components/ExportShortcut.vue
<template>
  <a-modal :visible="visible" title="Export Shortcut" @cancel="closeModal" @ok="exportAll">
    <div class="ant-modal-body">
      <export-outlined class="icon" />
      <p>Are you sure export all data?</p>
    </div>
  </a-modal>
</template>

<script>
import { ExportOutlined } from '@ant-design/icons-vue';
import { getAllShortcut } from '@/storage/crud';
import { showSaveDialog, exportFile } from '@/service/utils'

export default {
  name: 'ExportShortcut',
  components: {
    ExportOutlined
  },
  props: ['open', 'close'],
  data() {
    return {
      visible: false
    }
  },
  watch: {
    open: function () {
      this.openModal();
    },
    close: function () {
      this.closeModal();
    }
  },
  methods: {
    openModal() {
      this.visible = true
    },
    closeModal() {
      this.visible = false
    },
    exportAll() {
      getAllShortcut().then(rows => {
        const options = {
          title: "Export shortcuts",
          defaultPath: "export_shortcuts.json",
          buttonLabel: "Export",
          filters: [
            { name: 'json', extensions: ['json'] },
          ]
        };
        showSaveDialog(options).then(({ filePath }) => {
          if (filePath != undefined && filePath != '') {
            exportFile(filePath, JSON.stringify(rows), 'utf-8').then(() => {
              alert('All data exported successfully here ' + filePath)
            });
          }
        });
        this.closeModal()
      })
    }
  }
}
</script>

<style lang="scss" scoped>
.ant-modal-body {
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  gap: 10px;
}

.icon {
  color: #096dd9;
  font-size: 25px;
}
</style>
