// src/components/ClearShortcut.vue
<template>
  <a-modal
    :visible="visible"
    title="Clear Shortcut"
    @cancel="closeModal"
    @ok="clear"
  >
    <div class="ant-modal-body">
      <a-icon type="delete" class="icon" />
      <p>Are you sure delete data?</p>
    </div>
  </a-modal>
</template>

<script>
import { deleteAll } from "@/storage/crud";

export default {
  name: "ClearAllShortcut",
  props: ["open", "close"],
  emits: ['refresh'],
  data() {
    return {
      visible: false,
    };
  },
  watch: {
    open: function () {
      this.openModal();
    },
    close: function () {
      this.closeModal();
    },
  },
  methods: {
    openModal() {
      this.visible = true;
    },
    closeModal() {
      this.visible = false;
    },
    clear() {
      deleteAll().then(() => {
        this.$notification.success({
          message: "All data are deleted successfully"
        });
        this.refresh();
        this.closeModal();
      });
    },
    refresh() {
      this.$emit('refresh');
    }
  },
};
</script>

<style lang="scss" scoped>
.ant-modal-body {
  display: flex;
  flex-direction: row;
  justify-content: flex-start;
  gap: 10px;
}

.icon {
  color: #096dd9;
  font-size: 25px;
}
</style>

// src/component/ClearShortcutComponent.tsx
import { Modal } from "antd";
import { DeleteOutlined } from "@ant-design/icons";
import { notificationSuccess } from "./Notification";
import { deleteAll } from "../storage/crud";

import "../style/clear-style.scss"

function ClearShortcutComponent(props: { isOpen: boolean; closeModal: any, refresh: any }) {
  const close = () => {
    props.closeModal();
  };

  const clear = () => {
    deleteAll().then(() => {
      props.refresh();
      close();
      notificationSuccess({
        message: "All data are deleted successfully",
      });
    });
  };

  return (
    <Modal
      open={props.isOpen}
      title="Clear Shortcut"
      onCancel={close}
      onOk={clear}
    >
      <div className="clear-modal-content">
        <DeleteOutlined className="icon" />
        <p>Are you sure delete data?</p>
      </div>
    </Modal>
  );
}

export default ClearShortcutComponent;
